#!/bin/sh

set -e
# Any subsequent commands which fail will cause the shell script to exit immediately

linuxdeploy --executable NotesTree --desktop-file NotesTree.desktop --icon-file NotesTree.svg  --appdir AppDir --output appimage
