#!/bin/sh

mkdir -p appimage/usr/bin
mkdir -p appimage/usr/share/applications
mkdir -p appimage/usr/share/icons/hicolor/scalable/apps
mkdir -p appimage/usr/plugins/imageformats/
cp NotesTree appimage/usr/bin/
cp NotesTree.desktop appimage/usr/share/applications/
cp NotesTree.svg appimage/usr/share/icons/hicolor/scalable/apps
cp /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so appimage/usr/plugins/imageformats/
linuxdeployqt-continuous-x86_64.AppImage appimage/usr/share/applications/NotesTree.desktop -bundle-non-qt-libs -appimage -extra-plugins=svg
